# python test.py --base_model_type sd2 --base_model_path stabilityai/stable-diffusion-2-1-base --model_t 200 --coeff_t 200 --lora_rank 256 --lora_modules to_k,to_q,to_v,to_out.0,conv,conv1,conv2,conv_shortcut,conv_out,proj_in,proj_out,ff.net.2,ff.net.0.proj --weight_path model_pth/HYPIR_sd2.pth --patch_size 1024 --stride 256 --lq_dir /root/paddlejob/workspace/env_run/zhuyinghao/github/HYPIR/test_set_sr --scale_by factor --upscale 4 --captioner empty --output_dir ./result --seed 231 --device cuda --vae_batch_size 4 --generator_batch_size 4 --enable_fast_vae


# python test.py --base_model_type sd2 --base_model_path stabilityai/stable-diffusion-2-1-base --model_t 200 --coeff_t 200 --lora_rank 256 --lora_modules to_k,to_q,to_v,to_out.0,conv,conv1,conv2,conv_shortcut,conv_out,proj_in,proj_out,ff.net.2,ff.net.0.proj --weight_path model_pth/HYPIR_sd2.pth --patch_size 1024 --stride 256 --lq_dir /root/paddlejob/workspace/env_run/zhuyinghao/github/HYPIR/test_set_sr --scale_by factor --captioner empty --output_dir ./result --seed 231 --device cuda --vae_batch_size 4 --generator_batch_size 4 --enable_fast_vae --scale_by longest_side --target_longest_side 2048


# python test.py --base_model_type sd2 --base_model_path stabilityai/stable-diffusion-2-1-base --model_t 200 --coeff_t 200 --lora_rank 256 --lora_modules to_k,to_q,to_v,to_out.0,conv,conv1,conv2,conv_shortcut,conv_out,proj_in,proj_out,ff.net.2,ff.net.0.proj --weight_path model_pth/HYPIR_sd2.pth --patch_size 512 --stride 128 --lq_dir /root/paddlejob/workspace/env_run/zhuyinghao/github/HYPIR/test_set_sr --scale_by factor --captioner empty --output_dir ./result --seed 231 --device cuda --vae_batch_size 4 --generator_batch_size 4 --enable_fast_vae --scale_by longest_side --target_longest_side 2048


python test.py --base_model_type sd2 --base_model_path stabilityai/stable-diffusion-2-1-base --model_t 200 --coeff_t 200 --lora_rank 256 --lora_modules to_k,to_q,to_v,to_out.0,conv,conv1,conv2,conv_shortcut,conv_out,proj_in,proj_out,ff.net.2,ff.net.0.proj --weight_path model_pth/HYPIR_sd2.pth --patch_size 512 --stride 384 --lq_dir /root/paddlejob/workspace/env_run/guanfeiqiang/data/online_one_week120/test_online120_origin_max_2048 --scale_by factor --upscale 4 --captioner empty --output_dir ./result --seed 231 --device cuda --vae_batch_size 4 --generator_batch_size 4 --enable_fast_vae


# python test.py --base_model_type sd2 --base_model_path stabilityai/stable-diffusion-2-1-base --model_t 200 --coeff_t 200 --lora_rank 256 --lora_modules to_k,to_q,to_v,to_out.0,conv,conv1,conv2,conv_shortcut,conv_out,proj_in,proj_out,ff.net.2,ff.net.0.proj --weight_path model_pth/HYPIR_sd2.pth --patch_size 512 --stride 384 --lq_dir /root/paddlejob/workspace/env_run/guanfeiqiang/data/test100_rresize1024 --scale_by factor --upscale 4 --captioner empty --output_dir ./result --seed 231 --device cuda --vae_batch_size 4 --generator_batch_size 4 --enable_fast_vae