python test.py \
    --base_model_type sd2 \
    --base_model_path /path/to/sd2_model \
    --weight_path /path/to/weights.pth \
    --model_t 200 \
    --coeff_t 200 \
    --lora_rank 256 \
    --lora_modules "to_k,to_q,to_v,to_out.0,conv,conv1,conv2" \
    --lq_dir /path/to/input \
    --output_dir /path/to/output \
    --captioner empty \
    --patch_size 512 \
    --stride 256 \
    --vae_batch_size 8 \
    --generator_batch_size 4 \
    --enable_fast_vae \
    --enable_amp